services:
  backend:
    build:
      context: ./backend/server  # Update the path to the new location
      dockerfile: Dockerfile
    container_name: trading_backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    working_dir: /app/src
    environment:
      - MONGO_URI=mongodb://mongo:27017/tradingDB
      - PORT=3001
    networks:
      - trading_network

  mongo:
    image: mongo:latest
    container_name: trading_mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - trading_network
    volumes:
      - mongo_data:/data/db

networks:
  trading_network:

volumes:
  mongo_data: