services:
  backend:
    build:
      context: ./backend/server  # Update the path to the new location
      dockerfile: Dockerfile
    container_name: trading_backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis  # Ensure backend waits for Redis to start
    working_dir: /app/src
    environment:
      - MONGO_URI=mongodb://mongo:27017/tradingDB
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - trading_network

  mongo:
    image: mongo:latest
    container_name: trading_mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - trading_network
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: trading_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - trading_network
    volumes:
      - redis_data:/data

networks:
  trading_network:

volumes:
  mongo_data:
  redis_data:  # Added Redis volume for persistence